#!/usr/bin/expect
set timeout 20
set ip [lindex $argv 0]
set port [lindex $argv 1]
set user [lindex $argv 2]
set password [lindex $argv 3]

spawn ssh <username>@<dhcp-server-ip>
expect "no)?"
send "yes\r";
expect "Password:"
send "<userpassword>\r";
expect "#"
send "CoMMaND\r"
send "LeaSes\r"
#send "exit\r";

interact



